### ISSUE TITLE
Added some more automation to build_nginx2

### ISSUE THREAD

**Issue by wgroenewold** [poralix/directadmin-utils#1]
Hi,

Thanks so much for your awesome script. I updated it a bit so it checks automagically for the latest version of NGINX mainline in the hgtags file.

https://gist.github.com/wgroenewold/e852df0bd5e509dfb76eecac0e7a90b8

**Comment by poralix** [comment]
Hello,

Thank you for you modification. The build_nginx2 takes a mainline version from versions.txt, but there is [another edition of the script here build_nginx](https://github.com/poralix/directadmin-utils/blob/master/nginx/build_nginx), and this one takes a number of the version from NGINX's hgtags file. 

Thus users have a choice which version to choose, two editions of the script. Probably they will be unified in a future.
