### ISSUE TITLE
php-extension.sh and redis 5.x

### ISSUE THREAD

**Issue by centminmod** [poralix/directadmin-utils#5]
Just a heads up when you install redis php extension it seems by default the choice is redis 5.0.1. However, redis 5.x dropped PHP 5.x support https://pecl.php.net/package-changelog.php?package=redis&release=5.0.1.

So in your php-extension.sh redis routine you may want to conditionally check if php 5.x is being used and if so install redis 4.3.0 php extension and if php 7.x used, install redis 5.0.1 php extension.

**Comment by gralex54** [comment]
Hello,

Thank you for the request. Added in Commit 973b7e6
