### ISSUE TITLE
PHP Warning: Xdebug MUST be loaded as a Zend extension

### ISSUE THREAD

**Issue by anlicor** [poralix/directadmin-utils#8]
You need to change extension=xdebug.so to zend_extension=xdebug.so in 90-custom.ini or you will get 
"PHP Warning: Xdebug MUST be loaded as a Zend extension".
This may also be true for other extensions.

I had to manually change it in the files:
/usr/local/php8*/lib/php.conf.d/90-custom.ini;

To reproduce:
/usr/local/directadmin/scripts/custom/php-extension.sh install xdebug

Possible fixes?
Add a -zend flag maybe?

**Comment by gralex54** [comment]
Hello,

Thank you for the report. Fixed in the Commit 192f32f
